<?php

require_once '../Husky/bootstrap.php';


/**
 * Test class for FileSystem.
 * Generated by PHPUnit on 2011-08-07 at 21:53:52.
 */
class FileSystemTest extends PHPUnit_Framework_TestCase
{
    /**
     * @var Husky\Helper\FileSystem
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new \Husky\Helper\FileSystem;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @test
     * @todo Implement testGetFilesInDirectory().
     */
    public function getDirectoryTree_retuns_array()
    {
        $contents = $this->object->getDirectoryTree(APPLICATION_PATH . 'assets/');
        var_dump($contents);
    }

    /**
     * @test
     * @return void
     */
    public function getSubDirectories_returns_given_file_extension()
    {
        $contents = $this->object->getFileTree(APPLICATION_PATH . 'assets/');
        var_dump($contents);
    }
}

?>
