<?php
/**
 *
 * @author Ed van Beinum <e@edvanbeinum.com>
 * @version $Id$
 * @copyright Ibuildings 07/08/2011
 * @package HuskyTest
 */

require_once dirname(__FILE__) . '/../../../Husky/bootstrap.php';
require_once 'vfsStream/vfsStream.php';

/**
 * Test class for Page.
 * Generated by PHPUnit on 2011-08-07 at 21:53:52.
 */
class PageTest extends PHPUnit_Framework_TestCase
{
    /**
     * @var Husky\Helper\Page
     */
    protected $_page;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        //$this->_page = new \Husky\Helper\Page;

//        vfsStreamWrapper::register();
//        vfsStreamWrapper::setRoot(new vfsStreamDirectory('testDir'));
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
        unset($this->_page);
    }

    /**
     * @test
     */
    public function getPageTitle_returns_expected_string()
    {

    }

}