production:

  # Name of the Format type that the content is written in. Ships with Markdown or Textile
  formatter: Markdown

  # File extension of the content files
  formatterFileExtension: .md

  # Name of the Template Engine. Ships ith Twig or Mustache
  templateEngine: Twig

  # This is the file extenion that wil be used on the public site
  publicFileExtension: .html

  # Path, relative to Husky's root folder, where the content files live
  contentDirectory: assets/content

  # Path, relative to Husky's root folder, where the template layout file lives
  templatePath: assets/template/layout.html

  # Path, relative to Husky's root folder, where the finished public files will be written to
  publicDirectory: public


